# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' model
#' @name model
#' @inheritParams HydroGallery::all_vari
#' @param name_Region A short identifier of continents: "eu", "af, "as", "au", "na", "sa".
#' @param mark_Time A short identifier of time.
#' @param path_VariExport Directory path where model output variables (e.g., soil moisture, runoff) will be saved. If "NonExport", no variables will be exported.
#' @param path_FinalState Directory path where final state variables will be saved. If "NonExport", final states will not be saved.
#' @return streamflow m3
#' @export
WaterGAP3_U <- function(name_Region, mark_Time, n_time, n_spat, ATMOS_precipitation_mm, ATMOS_temperature_Cel, ATMOS_solarRadiat_MJ, ATMOS_solarRadiatClearSky_MJ, WITHDRAW_surface_m3, WITHDRAW_ground_m3, Reservoi_demand_m3, CELL_cellNumberAround_int, Upstream_cellNumber_int, Upstream_streamflow_m3, SNOW_ice_mm, LAND_area_km2, LAND_albedo_1, LAND_snowAlbedo_1, LAND_builtRatio_1, LAND_interceptWater_mm, LAND_interceptCapacity_mm, SOIL_water_mm, SOIL_capacity_mm, SOIL_potentialPercola_mm, GROUND_water_mm, RIVER_water_m3, RIVER_length_km, RIVER_velocity_km, CELL_elevation_m, CELL_cellNumberStep_int, CELL_inflowCellNumberStep_int, Lake_cellNumber_int, Lake_water_m3, Lake_area_km2, Lake_capacity_m3, Lake_albedo_1, Riverlak_cellNumber_int, Riverlak_water_m3, Riverlak_area_km2, Riverlak_capacity_m3, Riverlak_albedo_1, Reservoi_cellNumber_int, Reservoi_area_km2, Reservoi_capacity_m3, Reservoi_albedo_1, Reservoi_meanInflow_m3, Reservoi_meanDemand_m3, Reservoi_releaseCoefficient_1, Reservoi_dayIrrigate_int, param_ATMOS_thr_Ts, param_SNOW_fac_f, param_SNOW_fac_Tmelt, param_EVATRANS_prt_alpha, param_EVATRANS_vic_gamma, param_EVATRANS_sup_k, param_EVATRANS_sup_gamma, param_EVATRANS_wat_petmax, param_INFILT_hbv_beta, param_PERCOLA_wat_01, param_PERCOLA_wat_k, param_PERCOLA_wat_thresh, param_BASEFLOW_sur_k, param_Lake_acp_storeFactor, param_Lake_acp_gamma, param_Riverlak_lin_storeFactor, path_FinalState = "NonExport", path_VariExport = "NonExport") {
    .Call(`_WaterGAP3_WaterGAP3_U`, name_Region, mark_Time, n_time, n_spat, ATMOS_precipitation_mm, ATMOS_temperature_Cel, ATMOS_solarRadiat_MJ, ATMOS_solarRadiatClearSky_MJ, WITHDRAW_surface_m3, WITHDRAW_ground_m3, Reservoi_demand_m3, CELL_cellNumberAround_int, Upstream_cellNumber_int, Upstream_streamflow_m3, SNOW_ice_mm, LAND_area_km2, LAND_albedo_1, LAND_snowAlbedo_1, LAND_builtRatio_1, LAND_interceptWater_mm, LAND_interceptCapacity_mm, SOIL_water_mm, SOIL_capacity_mm, SOIL_potentialPercola_mm, GROUND_water_mm, RIVER_water_m3, RIVER_length_km, RIVER_velocity_km, CELL_elevation_m, CELL_cellNumberStep_int, CELL_inflowCellNumberStep_int, Lake_cellNumber_int, Lake_water_m3, Lake_area_km2, Lake_capacity_m3, Lake_albedo_1, Riverlak_cellNumber_int, Riverlak_water_m3, Riverlak_area_km2, Riverlak_capacity_m3, Riverlak_albedo_1, Reservoi_cellNumber_int, Reservoi_area_km2, Reservoi_capacity_m3, Reservoi_albedo_1, Reservoi_meanInflow_m3, Reservoi_meanDemand_m3, Reservoi_releaseCoefficient_1, Reservoi_dayIrrigate_int, param_ATMOS_thr_Ts, param_SNOW_fac_f, param_SNOW_fac_Tmelt, param_EVATRANS_prt_alpha, param_EVATRANS_vic_gamma, param_EVATRANS_sup_k, param_EVATRANS_sup_gamma, param_EVATRANS_wat_petmax, param_INFILT_hbv_beta, param_PERCOLA_wat_01, param_PERCOLA_wat_k, param_PERCOLA_wat_thresh, param_BASEFLOW_sur_k, param_Lake_acp_storeFactor, param_Lake_acp_gamma, param_Riverlak_lin_storeFactor, path_FinalState, path_VariExport)
}

#' @rdname model
#' @export
WaterGAP3_N <- function(name_Region, mark_Time, n_time, n_spat, ATMOS_precipitation_mm, ATMOS_temperature_Cel, ATMOS_solarRadiat_MJ, ATMOS_solarRadiatClearSky_MJ, Upstream_cellNumber_int, Upstream_streamflow_m3, SNOW_ice_mm, LAND_area_km2, LAND_albedo_1, LAND_snowAlbedo_1, LAND_builtRatio_1, LAND_interceptWater_mm, LAND_interceptCapacity_mm, SOIL_water_mm, SOIL_capacity_mm, SOIL_potentialPercola_mm, GROUND_water_mm, RIVER_water_m3, RIVER_length_km, RIVER_velocity_km, CELL_elevation_m, CELL_cellNumberStep_int, CELL_inflowCellNumberStep_int, Lake_cellNumber_int, Lake_water_m3, Lake_area_km2, Lake_capacity_m3, Lake_albedo_1, Riverlak_cellNumber_int, Riverlak_area_km2, Riverlak_capacity_m3, Riverlak_albedo_1, param_ATMOS_thr_Ts, param_SNOW_fac_f, param_SNOW_fac_Tmelt, param_EVATRANS_prt_alpha, param_EVATRANS_vic_gamma, param_EVATRANS_sup_k, param_EVATRANS_sup_gamma, param_EVATRANS_wat_petmax, param_INFILT_hbv_beta, param_PERCOLA_wat_01, param_PERCOLA_wat_k, param_PERCOLA_wat_thresh, param_BASEFLOW_sur_k, param_Lake_acp_storeFactor, param_Lake_acp_gamma, param_Riverlak_lin_storeFactor, path_FinalState = "NonExport", path_VariExport = "NonExport") {
    .Call(`_WaterGAP3_WaterGAP3_N`, name_Region, mark_Time, n_time, n_spat, ATMOS_precipitation_mm, ATMOS_temperature_Cel, ATMOS_solarRadiat_MJ, ATMOS_solarRadiatClearSky_MJ, Upstream_cellNumber_int, Upstream_streamflow_m3, SNOW_ice_mm, LAND_area_km2, LAND_albedo_1, LAND_snowAlbedo_1, LAND_builtRatio_1, LAND_interceptWater_mm, LAND_interceptCapacity_mm, SOIL_water_mm, SOIL_capacity_mm, SOIL_potentialPercola_mm, GROUND_water_mm, RIVER_water_m3, RIVER_length_km, RIVER_velocity_km, CELL_elevation_m, CELL_cellNumberStep_int, CELL_inflowCellNumberStep_int, Lake_cellNumber_int, Lake_water_m3, Lake_area_km2, Lake_capacity_m3, Lake_albedo_1, Riverlak_cellNumber_int, Riverlak_area_km2, Riverlak_capacity_m3, Riverlak_albedo_1, param_ATMOS_thr_Ts, param_SNOW_fac_f, param_SNOW_fac_Tmelt, param_EVATRANS_prt_alpha, param_EVATRANS_vic_gamma, param_EVATRANS_sup_k, param_EVATRANS_sup_gamma, param_EVATRANS_wat_petmax, param_INFILT_hbv_beta, param_PERCOLA_wat_01, param_PERCOLA_wat_k, param_PERCOLA_wat_thresh, param_BASEFLOW_sur_k, param_Lake_acp_storeFactor, param_Lake_acp_gamma, param_Riverlak_lin_storeFactor, path_FinalState, path_VariExport)
}

#' run_model
#' @name run_model
#' @description
#' Run WaterGAP3_N hydrological model
#'
#' This function runs the WaterGAP3_N hydrological model for a specified region
#' and time period, returning discharge calculations.
#'
#' @inheritParams model
#' @param path_MeteoInput Directory path containing meteorological input files.
#' @param path_WateruseInput Directory path containing wateruse input files.
#' @param path_HydroParam Directory path containing hydrological parameter files.
#' @param path_InitialState Directory path containing initial state files. If "UNKNOW", default initial states will be used.
#' @param path_Boundary Directory path containing boundary condition files. If "UNKNOW", default boundary conditions will be used.
#'
#' @return A numeric matrix (CELL_discharge_m3) containing discharge values for each cell and time step.
#' @export
run_WaterGAP3_U <- function(name_Region, mark_Time, n_Time, n_Spat, path_MeteoInput, path_HydroParam, path_WateruseInput, path_InitialState = "UNKNOW", path_Boundary = "UNKNOW", path_VariExport = "NonExport", path_FinalState = "NonExport") {
    .Call(`_WaterGAP3_run_WaterGAP3_U`, name_Region, mark_Time, n_Time, n_Spat, path_MeteoInput, path_HydroParam, path_WateruseInput, path_InitialState, path_Boundary, path_VariExport, path_FinalState)
}

#' @rdname run_model
#' @export
run_WaterGAP3_N <- function(name_Region, mark_Time, n_Time, n_Spat, path_MeteoInput, path_HydroParam, path_InitialState = "UNKNOW", path_Boundary = "UNKNOW", path_VariExport = "NonExport", path_FinalState = "NonExport") {
    .Call(`_WaterGAP3_run_WaterGAP3_N`, name_Region, mark_Time, n_Time, n_Spat, path_MeteoInput, path_HydroParam, path_InitialState, path_Boundary, path_VariExport, path_FinalState)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_WaterGAP3_RcppExport_registerCCallable`)
})
